<?php 
	include('contenedores/estatico/emp/head.html');
	include('contenedores/estatico/nav.html');
	if(isset($_REQUEST['id'])){
		include('../control/cDetalleMuseo.php');		
	}else{
		include('../control/cBusqueda.php');
	}
	include('contenedores/estatico/emp/footer.html');
?>