/*
	ESTE ARCHIVO CONTIENE LOS PL-SQL Y TRRIGERS USADOS EN LA
	TABLA DE LA BITACORA

	CONTENIDO
		-PL-SQL
		-TRIGGERS

	NOTAS
		-LA FECHA QUE SE MUESTRA ESTA FORMATEADA
			ANTES
				AÑO(4 DIGITOS)-MES-DIA HORA(24):MINUTOS:SEGUNDOS
			DESPUES
				DIA-MES-AÑO(2 DIGITOS) HORA(12):MINUTOS:SEGUNDOS (AM/PM)
*/

DELIMITER $$
CREATE PROCEDURE bitacora_insertar(IN bit_USU VARCHAR(30),IN bit_TABLA VARCHAR(30),IN bit_TRAN VARCHAR(500),IN bit_DESC VARCHAR(200))
	BEGIN
		INSERT BITACORA VALUES(NULL,bit_USU,bit_TABLA,bit_TRAN,bit_DESC,NOW());
	END $$
DELIMITER;

DELIMITER $$
CREATE PROCEDURE getAllBitacora()
  BEGIN
    SELECT bit_ID,bit_USU,bit_TABLA,bit_TRAN,bit_DESC,DATE_FORMAT(BIT_FECHA,'%d/%m/%y %r') "bit_FECHA"
    FROM bitacora order by bit_ID desc;
  END $$
DELIMITER;


